### ISSUE TITLE
modified version

### ISSUE THREAD

**Issue by wolfgang6444** [devttys0/libmpsse#24]
I have created a modified version with the following additional features:

1) JTAG support
2) Simultaneous READ/WRITE also for word-length that are no integer multiples of 8-Bits.
3) READ back of the pin-state also for GPIOH
4) Seamless switching from JTAG to SPI (and possibly I2C) and back
5) Simultaneous use of GPIO with JTAG and/or SPI (and possibly I2C)

If somebody is interested or wants to add it to GitHub please drop me a note.
I have no experience with GitHub

Kind regard!

Wolfgang

**Comment by Cosik** [comment]
Hi Wolfgang

Could you share yours modified version? I see that most of libmpsse projects are dead, I also see some problems with method of return read values, etc.

**Comment by wolfgang6444** [comment]
Sure,

my code is attached (I don't think I am allowed to commit to GitHub).
I am currenly working on adding RS232 support to have it all in a single lib.

Kind regards,

Wolfgang
[libmpsse_1.4.zip](https://github.com/devttys0/libmpsse/files/714443/libmpsse_1.4.zip)

**Comment by wolfgang6444** [comment]
I have added support for RS232 and corrected some minor bugs

Wolfgang
[libmpsse_1.5.zip](https://github.com/devttys0/libmpsse/files/721880/libmpsse_1.5.zip)

**Comment by wolfgang6444** [comment]
I have added a version with bug corrections for JTAG.
Has been tested with a real live device.

Wolfgang
[libmpsse_1.6.zip](https://github.com/devttys0/libmpsse/files/814578/libmpsse_1.6.zip)
