### ISSUE TITLE
FT232 UART device gets disconnected when an SPI device is run

### ISSUE THREAD

**Issue by skrishnamoorthy5287** [devttys0/libmpsse#35]
Hello, 

I'm using the library to try and talk to a device using SPI over a USB interface with a Raspberry Pi. Two other RS-232 to USB cables are connected to the USB port. When I run a simple code that establishes a connection and pulls data out of the SPI device, one of the the other two devices stops appearing in the /dev/ttyUSB* list and I can't communicate with it anymore. Is there any solution to this problem? 

Thanks,

Siddharth

**Comment by l29ah** [comment]
Have you tried `OpenIndex()`?

**Comment by skrishnamoorthy5287** [comment]
I believe the Open function essentially uses the OpenIndex function, right?

I have three devices connected to my RPi. If I do: 
ls /dev/ttyUSB* 

it shows me all three connected (USB0, USB1, USB2). Then I run a code which only implements:
spi=MPSSE(SPI0,ONE_HUNDRED_KHZ,MSB)

after which when I do ls /dev/ttyUSB* again, only USB0 and USB1 are shown. But if I do lsusb, I can still see all three devices there. 

Quite confused by this behaviour. 

Thank you for your help.

**Comment by skrishnamoorthy5287** [comment]
Ah thank you. I was concerned it was kicking one of my devices off, but I looked in further and it looks like it first identifies itself as a UART device, that's why I see 3 USB connections, but once I set up the SPI it removes itself from the UART list. 

Thank you for your guidance and sorry for the ignorance, first time using SPI over USB with other devices in there :)
