### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by AndreiUngureanu101** [devttys0/libmpsse#42]
Hello! Is there any way to install this library for python 3? I've seen some forks that change some part of the code to be compatible with python 3 but they don't seem to address the issues regarding the libraries compiled specifically for python 2.

**Comment by AndreiUngureanu101** [comment]
Never mind, I got it to work in python3

**Comment by BreakfastSerial** [comment]
I'm positive more people want to run spiflash.py with python3. Would you share your approach?
